{"name": "test_16_form_authentication_wrong_username", "status": "passed", "steps": [{"name": "Открытие главной страницы сайта", "status": "passed", "start": 1665523086776, "stop": 1665523088841}, {"name": "Открытие страницы с примером Form Authentication", "status": "passed", "start": 1665523088841, "stop": 1665523089449}, {"name": "Заполнение формы username с ошибкой", "status": "passed", "start": 1665523089449, "stop": 1665523089539}, {"name": "Заполнение формы password", "status": "passed", "start": 1665523089539, "stop": 1665523089636}, {"name": "Нажатие кнопки Login", "status": "passed", "start": 1665523089636, "stop": 1665523090052}], "attachments": [{"name": "stdout", "source": "2d3d822c-566c-47e7-b709-0da5feef03ee-attachment.txt", "type": "text/plain"}], "start": 1665523086775, "stop": 1665523090075, "uuid": "ed1733c0-5407-430e-9c29-320ef7b1bef6", "historyId": "53c0e9b6ce66dd065478d37e3c20f176", "testCaseId": "6ad7037b129c9db4e35c48f222500441", "fullName": "diploma.pom.tests.test_pt_5_auth_pages#test_16_form_authentication_wrong_username", "labels": [{"name": "suite", "value": "Авторизации с ошибкой в username"}, {"name": "feature", "value": "Проверка авторизации c ошибкой в username"}, {"name": "tag", "value": "@pytest.mark.usefixtures('text_inside_test')"}, {"name": "parentSuite", "value": "diploma.pom.tests"}, {"name": "host", "value": "DESKTOP-I5N6LU0"}, {"name": "thread", "value": "29948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "diploma.pom.tests.test_pt_5_auth_pages"}]}